apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-server
  labels:
    app: uwsgi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uwsgi-app
  template:
    metadata:
      labels:
        app: uwsgi-app
    spec:
      containers:
      - name: uwsgi-container
        image: taichikawai/uwsgi-app:v4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-src
          mountPath: /app
      volumes:
      - name: app-src
        hostPath:
          path: /home/user/test/src  # ホスト側のソースコードディレクトリ（例）

---
apiVersion: v1
kind: Service
metadata:
  name: uwsgi-service
spec:
  selector:
    app: uwsgi-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

