apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config # ConfigMapの名前
data:
  nginx.conf: |       # ConfigMap内にNginx設定ファイルを直接記述
    events { }

    http {
        server {
            listen 8080; # 外部リクエストのポート
            server_name 127.0.0.1;

            location / {
                proxy_pass http://10.104.48.154:8080; # リバースプロキシ先の内部サーバー
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
