apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: nginx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config       # コンテナ内のマウント先ディレクトリ
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config                # 作成したConfigMapの名前
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

